### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by Molly82742** [imartemy1524/vk_audio#10]
`
	vk = vk_audio.VkAudio(login=my_login, password=my_password)
	
	artist = input('Enter artist name: ')
	audios = vk.load_artist(artist)
	audios = audios.Audios
	
	for n, audio in enumerate(audios, 1):
		audio.add()
		
		str = '{} – {}'.format(audio.artist, audio.title)
		print(str)
`

Traceback (most recent call last):
  File "a/vk_bot.py", line 20, in <module>
    main()
  File "a/vk_bot.py", line 14, in main
    audio.add()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/vk_audio/audio_obj.py", line 208, in add
    self.as_object(item);
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/vk_audio/audio_obj.py", line 18, in as_object
    self.image=json[self.enum.AUDIO_ITEM_INDEX_COVER_URL]
IndexError: string index out of range

**Comment by Molly82742** [comment]
это происходит после 25 трека, когда надо вводить капчу.

**Comment by Molly82742** [comment]
добавьте возможность передать функцию обработки капчи
